#!/bin/bash

# Add node_exporter user

sudo useradd --no-create-home node_exporter

# Download Node Exporter

wget https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz

# Extract Node Exporter

tar -xf node_exporter-1.8.1.linux-amd64.tar.gz

# Move Node Exporter binary to /usr/local/bin

sudo mv node_exporter-1.8.1.linux-amd64/node_exporter /usr/local/bin/node_exporter

# Clean up downloaded files

rm -rf node_exporter-1.8.1.linux-amd64*

# Create systemd service file for Node Exporter

sudo tee /etc/systemd/system/node-exporter.service > /dev/null <<EOF

[Unit]

Description=Prometheus Node Exporter Service

After=network.target

[Service]

User=node_exporter

Group=node_exporter

Type=simple

ExecStart=/usr/local/bin/node_exporter

[Install]

WantedBy=multi-user.target

EOF

# Reload systemd to load new service file

sudo systemctl daemon-reload

# Enable and start Node Exporter service

sudo systemctl enable node-exporter

sudo systemctl start node-exporter

# Check Node Exporter service status

sudo systemctl status node-exporter
